{% set name = "langgraph-checkpoint" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langgraph_checkpoint-{{ version }}.tar.gz
  sha256: 31c34952b11a93108d76e5ad05398bfc94d8aafda5b4da7d17c26a121acce8e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - msgpack-python >=1.1.0,<2.0.0
    - python >=3.9.0,<4.0.0,<4.0
    - langchain-core >=0.2.38,<0.4

test:
  imports:
    - langgraph.checkpoint.memory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: Library with base interfaces for LangGraph checkpoint savers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
