{% set name = "langgraph-checkpoint" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langgraph_checkpoint-{{ version }}.tar.gz
  sha256: 7f46b033888923ae4521ca2c9ccfcba6aacc7121888d77a6da1fd41ac2768d52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0,<4.0
    - langchain-core >=0.2.22,<0.3

test:
  imports:
    - langgraph.checkpoint.memory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: Library with base interfaces for LangGraph checkpoint savers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
