{% set name = "langgraph-checkpoint" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 72038c0f9e22260cb9bff1f3ebe5eb06d940b7ee5c1e4765019269d4f21cf92d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - ormsgpack >=1.10.0
    - langchain-core >=0.2.38

test:
  source_files:
    - tests
  imports:
    - langgraph.checkpoint.base
    - langgraph.checkpoint.base.id
    - langgraph.checkpoint.memory
    - langgraph.checkpoint.serde.base
    - langgraph.checkpoint.serde.jsonplus
    - langgraph.checkpoint.serde.types
  requires:
    - pip
    - pytest
    - pytest-mock
    - pytest-tornasync
    - numpy
    - pandas
    - dataclasses-json
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://www.github.com/langchain-ai/langgraph
  summary: Library with base interfaces for LangGraph checkpoint savers.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    This library defines the base interface for LangGraph checkpointers. Checkpointers provide a persistence layer for LangGraph.
    They allow you to interact with and manage the graph's state. When you use a graph with a checkpointer, the checkpointer saves
    a checkpoint of the graph state at every superstep, enabling several powerful capabilities like human-in-the-loop,
    "memory" between interactions and more.
  dev_url: https://github.com/langchain-ai/langgraph/tree/main/libs/checkpoint
  doc_url: https://github.com/langchain-ai/langgraph/blob/main/libs/checkpoint/README.md

extra:
  recipe-maintainers:
    - jan-janssen